[package]
name = "opentype"
version = "0.3.3"
authors = ["Ivan Ukhov <ivan.ukhov@gmail.com>"]
license = "MIT"
repository = "https://github.com/bodoni/opentype"
homepage = "https://github.com/bodoni/opentype"
documentation = "https://bodoni.github.io/opentype"
description = "The package provides a parser for OpenType fonts."

[dependencies]
truetype = { git = "https://github.com/bodoni/truetype.git" }

[[test]]
name = "opentype"
path = "tests/lib.rs"
