[package]
name = "opentype"
version = "0.19.0"
edition = "2018"
license = "Apache-2.0/MIT"
authors = [
    "Ivan Ukhov <ivan.ukhov@gmail.com>",
    "Simon Sapin <simon.sapin@exyr.org>",
]
description = "The package provides a parser for OpenType fonts."
documentation = "https://docs.rs/opentype"
homepage = "https://github.com/bodoni/opentype"
repository = "https://github.com/bodoni/opentype"
readme = "README.md"
exclude = ["tests/fixtures/*"]

[dependencies]
postscript = "0.14"
truetype = "0.30"
