[package]
name = "opentype"
version = "0.16.0"
license = "Apache-2.0/MIT"
authors = ["Ivan Ukhov <ivan.ukhov@gmail.com>"]
description = "The package provides a parser for OpenType fonts."
documentation = "https://bodoni.github.io/opentype"
homepage = "https://github.com/bodoni/opentype"
repository = "https://github.com/bodoni/opentype"
exclude = ["tests/fixtures/*"]

[dependencies]
postscript = "0.11"
truetype = "0.20"
