[package]
name = "opentype"
version = "0.1.1"
authors = ["Ivan Ukhov <ivan.ukhov@gmail.com>"]
license = "MIT"
repository = "https://github.com/stainless-steel/opentype"
homepage = "https://github.com/stainless-steel/opentype"
description = "The package provides a parser for OpenType fonts."

[dependencies]
date = "*"
