[package]
name = "opentype"
version = "0.0.4"
authors = ["Ivan Ukhov <ivan.ukhov@gmail.com>"]
license = "MIT"
repository = "https://github.com/stainless-steel/opentype"
homepage = "https://github.com/stainless-steel/opentype"
description = "The library provides a parser for OpenType fonts."

[dependencies]
date = "0.0.6"

[dev-dependencies]
assert = "0.0.2"
