[package]
name = "opentype"
version = "0.6.0"
authors = ["Ivan Ukhov <ivan.ukhov@gmail.com>"]
license = "MIT"
repository = "https://github.com/bodoni/opentype"
homepage = "https://github.com/bodoni/opentype"
documentation = "https://bodoni.github.io/opentype"
description = "The package provides a parser for OpenType fonts."

[dependencies]
postscript = "0.3"
truetype = "0.5"
